### ISSUE TITLE
Arrow function style

### ISSUE THREAD

**Issue by sabrehagen** [xsburg/vscode-javascript-booster#10]
When executing `Add braces to arrow function statement` on 
```js
const example = (args) => args;
```
it yields
```js
const example = args => {
  return args;
};
```
How can I configure the plugin to also apply `Wrap parameter with ()` in the same operation to produce
```js
const example = (args) => {
  return args;
};
```
with only one code action?

**Comment by xsburg** [comment]
Hi,

Good question. When manipulating the code, the extension tries to preserve the existing formatting but it isn't possible in some cases. For these situations, default formatting options are applied, which is basically what happens in the case that you mention.

These default formatting options are hardcoded now but could be easily exposed via extension settings. I'll publish an updated version soon and it will fix the problem. You'll just have to set `arrowParensAlways: true` to adjust the behavior.

Also, I would recommend using [Prettier](https://github.com/prettier/prettier-vscode) to preserve code style automatically. When configured to format on save, such formatting issues become barely noticable imo.

Cheers!

**Comment by xsburg** [comment]
Fixed with the option `javascriptBooster.formattingOptions` in v0.11.0.
