### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by kolde43** [xsburg/vscode-javascript-booster#11]
please dont stop development .. this is really useful

**Comment by maricn** [comment]
Can we buy you a coffee or support the development effort by donating?

**Comment by xsburg** [comment]
Thank you very much for your support, it motivates a lot!

@maricn, I'll be happy to accept a donation through [PayPal](https://www.paypal.me/xsburg). Thank you for the idea, I've updated the contribution section in readme.
