### ISSUE TITLE
Ternary ( Replace if-else with ?:)

### ISSUE THREAD

**Issue by plonko** [xsburg/vscode-javascript-booster#14]
![image](https://user-images.githubusercontent.com/629571/53008338-0f861c80-3431-11e9-8490-66586a576a15.png)

Hey, this is great, thanks very much. Looking forward to using via quick fix. One thing I installed for but could get working is "Replace if-else with ?:"
Any ideas why the above example wouldn't trigger a quick fix option to replace with ternary?
Thanks

**Comment by xsburg** [comment]
Released in v0.11.0.
