### ISSUE TITLE
How to activate "Convert shorthand arrow function to statement"

### ISSUE THREAD

**Issue by skidding** [xsburg/vscode-javascript-booster#16]
Hello,

Thanks for this awesome VSCode extension!

I'm trying to use the `Convert shorthand arrow function to statement` function but I can't find the option in my code?

Here's an example:
![image](https://user-images.githubusercontent.com/250750/56274300-2a120480-6107-11e9-8680-62d48c545c8f.png)

What are the requirements for this transform to become available?

**Comment by xsburg** [comment]
Hello @skidding,

The general logic behind most code actions in this extension is that you don't need to select the whole statement for it to work. Instead, it's just enough to place the cursor at the right place. In this particular case - somewhere near the arrow:

![image](https://user-images.githubusercontent.com/830824/56278636-e0c1b500-6106-11e9-8c09-b4a0ec664855.png)

Cheers!

**Comment by skidding** [comment]
@xsburg Thanks, that seems to work!
