### ISSUE TITLE
Can you create a small extension like this..

### ISSUE THREAD

**Issue by techsin** [xsburg/vscode-javascript-booster#2]
First great extension. Love it. Will give feedback after I've used it more.
But I also have been looking for something like this..

https://github.com/Microsoft/vscode/issues/45631

**Comment by xsburg** [comment]
Hi @techsin,
The idea of moving individual cursors might be interesting when doing a complicated refactoring.
However, I have a few reservations about the complexity and whether the tasks could be achieved through the existing features of multi-cursors.
Can you provide more practical examples where it's useful?

**Comment by techsin** [comment]
Often when writing with multiple cursors it's awesome you're able to write 10 lines simultaneously, but there comes time where you want to have different value, and then continue from there..

example

http://g.recordit.co/7E4mAJz0L9.gif

**Comment by techsin** [comment]
![image](http://g.recordit.co/7E4mAJz0L9.gif)

**Comment by techsin** [comment]
Think Excel, when you lot of data to put you can just press enter and keep typing. 
Similarly, here I was thinking. Press shortcut -> enter into mode. Press tab to cycle through cursors. Press ESC to go back to regular multiple cursors.

**Comment by xsburg** [comment]
Thanks for the example.
I think what you are looking for might be using multi-cursors like this:

![](http://g.recordit.co/FPpFNy361N.gif)

You can also transform the items before inserting them, which is extremely useful.

In general, I believe the idea of manipulating individual cursors (like in [this Sublime extension](https://github.com/MaokaiLin/PowerCursors)) is quite interesting. Might be worth implementing it as a separate extension, but it's not on my roadmap yet.

**Comment by techsin** [comment]
that's a good work around for now, thanks
