### ISSUE TITLE
feature request: split self closed JSX tag into an opening and closing tag

### ISSUE THREAD

**Issue by capaj** [xsburg/vscode-javascript-booster#3]
this
```
<div />
```

into this:
```
<div>

</div>
```

**Comment by xsburg** [comment]
Hi @capaj!
In fact, I've already implemented this code action:

![collapseexpand](https://user-images.githubusercontent.com/830824/38187761-b196769c-3661-11e8-8c2a-b93e028b796e.gif)

Please check that the extension is updated to the latest version (0.5.0 at the moment).
If it still doesn't work, data from the Output window might give us a hint of what's wrong.

Thanks!

**Comment by capaj** [comment]
I totaly missed it-works great. Too bad the readme does not have a GIF for each action :pensive:

**Comment by xsburg** [comment]
Great! 🎉
Adding animations for each action is definitely a good idea. Will give it an extra thought.
