### ISSUE TITLE
Extend/Shrink selections fallback not working

### ISSUE THREAD

**Issue by geoff-harper** [xsburg/vscode-javascript-booster#4]
When I try to use the command I bound (Cmd + W, Cmd + Shift + W) in an unsupported file, I get a notification saying that the command is not found.

```
// Specifies the fallback command that should be executed if the file is not supported by smart selection.
"javascriptBooster.smartExtendFallbackCommand": "editor.action.smartSelect.grow",

// Specifies the fallback command that should be executed if the file is not supported by smart selection.
"javascriptBooster.smartShrinkFallbackCommand": "editor.action.smartSelect.shrink"
```

I haven't changed the keybindings of the default commands. I'm on v0.6.0 for the extension and v1.22.2 for VSCode.

**Comment by xsburg** [comment]
Hi @geoff-harper,

Thanks for reporting! I see what the problem is and will fix it shortly. I'll publish the new version in an day or two after I've tested all the changes pending for the release.

Cheers! 🎉
