### ISSUE TITLE
Bad performance while typing

### ISSUE THREAD

**Issue by jrieken** [xsburg/vscode-javascript-booster#6]
* install this extension
* work on vscode, open `vscode.d.ts`
* type inside a doc comment
* everything is slow 🐌 
* profile running extensions via the 'F1 > Show Running Extensions' and notice that this extension parses the file in process, see attached CPU-profile

[CPU-20180502T092042.282Z.cpuprofile.txt](https://github.com/xsburg/vscode-javascript-booster/files/1966659/CPU-20180502T092042.282Z.cpuprofile.txt)

<img width="765" alt="screen shot 2018-05-02 at 11 22 27" src="https://user-images.githubusercontent.com/1794099/39515779-61ee4622-4dfb-11e8-99c7-1e2fcc39613f.png">

**Comment by jrieken** [comment]
It would be beneficial if this extension follows the guidance provided here: https://code.visualstudio.com/docs/extensions/overview#_language-servers

**Comment by xsburg** [comment]
Thanks for pointing this out, the problem speaks for itself. I will focus on this issue and extract the AST logic into a language server in the upcoming release.

**Comment by xsburg** [comment]
Hi @jrieken,

I've addressed this issue in release 0.8.0, all AST-related logic is now isolated into a language server and the overall performance seems to be much better. There are still things that could easily boost the performance of the server itself, I'm going to address it in future versions.

I suppose it is now usable for working with large files and doesn't deteriorate user experience. Thanks a lot for bringing this up and please report any problems you might come across. I really appreciate any feedback.

Cheers! 🎉
